import os
import datetime
from fpdf import FPDF
from PIL import Image
import tempfile
import cv2
import matplotlib.pyplot as plt
import numpy as np

class ReportPDF(FPDF):
    def header(self):
        self.set_fill_color(6, 78, 59) # Deep Green background
        self.rect(0, 0, 210, 25, 'F')
        self.set_text_color(255, 255, 255)
        self.set_font('Arial', 'B', 18)
        self.set_xy(10, 8)
        self.cell(0, 10, 'PlantGuard AI - Diagnostic Report', 0, 1, 'C')
        self.ln(12)
        self.set_text_color(0, 0, 0) # Reset

    def footer(self):
        self.set_y(-15)
        self.set_text_color(128, 128, 128)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by PlantGuard AI', 0, 0, 'C')

def create_probability_chart(probabilities, temp_dir):
    """Generates a horizontal bar chart of the top 3 predictions."""
    if not probabilities:
        return None
        
    sorted_probs = sorted(probabilities.items(), key=lambda item: item[1], reverse=True)[:3]
    labels = [k.replace('_', ' ') for k, v in sorted_probs]
    values = [v * 100 for k, v in sorted_probs]
    
    plt.figure(figsize=(7, 3))
    colors = ['#10b981' if i == 0 else '#94a3b8' for i in range(len(values))]
    plt.barh(labels[::-1], values[::-1], color=colors[::-1], height=0.6)
    plt.xlabel('Probability (%)', fontsize=10)
    plt.title('AI Confidence Distribution', fontsize=12, fontweight='bold')
    plt.xlim(0, 100)
    plt.tight_layout()
    
    chart_path = os.path.join(temp_dir, "prob_chart.png")
    plt.savefig(chart_path, dpi=150, bbox_inches='tight')
    plt.close()
    return chart_path

def generate_pdf_report(original_img, heatmap_img, prediction_data, disease_info):
    """
    Generates a PDF report for a prediction.
    
    Args:
        original_img: PIL Image of the uploaded leaf.
        heatmap_img: numpy array of the Grad-CAM heatmap superimposed image.
        prediction_data: dict containing prediction results.
        disease_info: dict containing disease information.
        
    Returns:
        str: Path to the generated PDF file.
    """
    pdf = ReportPDF()
    pdf.add_page()
    
    # Title & Metadata
    pdf.set_font('Arial', 'B', 14)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 10, 'Diagnostic Summary', 0, 1)
    
    pdf.set_font('Arial', '', 11)
    pdf.cell(0, 6, f'Date of Analysis: {datetime.datetime.now().strftime("%B %d, %Y - %H:%M:%S")}', 0, 1)
    
    status = "Healthy" if prediction_data['is_healthy'] else "Diseased"
    pdf.cell(0, 6, f'Primary Detection: {prediction_data["predicted_class"].replace("_", " ")}', 0, 1)
    
    if not prediction_data['is_healthy']:
        severity = "High" if prediction_data['confidence'] > 0.8 else "Moderate"
        pdf.set_text_color(220, 38, 38) if severity == "High" else pdf.set_text_color(217, 119, 6)
        pdf.cell(0, 6, f'Severity Level: {severity}', 0, 1)
    else:
        pdf.set_text_color(16, 185, 129)
        pdf.cell(0, 6, f'Status: {status}', 0, 1)
        
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 6, f'Confidence Score: {prediction_data["confidence"] * 100:.2f}%', 0, 1)
    
    # Draw a line
    pdf.ln(5)
    pdf.set_draw_color(226, 232, 240)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)
    
    # Images (We need to save them temporarily to add to PDF)
    temp_dir = tempfile.gettempdir()
    orig_path = os.path.join(temp_dir, "orig_leaf.jpg")
    heat_path = os.path.join(temp_dir, "heat_leaf.jpg")
    
    original_img.convert('RGB').save(orig_path)
    
    if heatmap_img is not None:
        cv2.imwrite(heat_path, cv2.cvtColor(heatmap_img, cv2.COLOR_RGB2BGR))
        
    # Generate Chart
    chart_path = create_probability_chart(prediction_data.get('all_probabilities', {}), temp_dir)
    
    # Add images side by side
    pdf.set_font('Arial', 'B', 12)
    pdf.set_text_color(71, 85, 105)
    pdf.cell(95, 10, 'Scanned Specimen:', 0, 0, 'C')
    if heatmap_img is not None:
        pdf.cell(95, 10, 'AI Focus Area (Grad-CAM):', 0, 1, 'C')
    else:
        pdf.ln(10)
        
    y_before_images = pdf.get_y()
    pdf.image(orig_path, x=10, y=y_before_images, w=80)
    
    if heatmap_img is not None:
        pdf.image(heat_path, x=110, y=y_before_images, w=80)
    
    pdf.set_y(y_before_images + 85) # Move cursor below images
    
    # Add chart
    if chart_path:
        pdf.image(chart_path, x=25, y=pdf.get_y(), w=160)
        pdf.set_y(pdf.get_y() + 75)
    
    pdf.set_draw_color(226, 232, 240)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)
    
    # Disease Info
    if not prediction_data['is_healthy']:
        pdf.set_font('Arial', 'B', 14)
        pdf.set_text_color(15, 23, 42)
        pdf.cell(0, 10, 'Agronomist Analysis & Action Plan', 0, 1)
        pdf.ln(2)
        
        # Helper to format sections
        def add_section(title, content):
            pdf.set_font('Arial', 'B', 11)
            pdf.set_text_color(6, 78, 59) # Deep green
            pdf.cell(0, 6, title, 0, 1)
            
            pdf.set_font('Arial', '', 11)
            pdf.set_text_color(51, 65, 85) # Slate grey
            # Indent text slightly
            pdf.set_x(15)
            pdf.multi_cell(0, 6, content)
            pdf.ln(4)

        add_section('Description:', disease_info.get("description", "N/A"))
        add_section('Symptoms to Look For:', disease_info.get("symptoms", "N/A"))
        add_section('Root Causes:', disease_info.get("causes", "N/A"))
        
        # Highlight Prevention
        pdf.set_font('Arial', 'B', 11)
        pdf.set_text_color(220, 38, 38) # Red
        pdf.cell(0, 6, 'Prevention & Care:', 0, 1)
        pdf.set_font('Arial', '', 11)
        pdf.set_text_color(51, 65, 85)
        pdf.set_x(15)
        pdf.multi_cell(0, 6, disease_info.get("prevention", "N/A"))
        
    # Clean up temp files
    try:
        os.remove(orig_path)
        if heatmap_img is not None:
            os.remove(heat_path)
        if chart_path:
            os.remove(chart_path)
    except Exception:
        pass
        
    report_path = os.path.join(temp_dir, f"PlantGuard_Report_{datetime.datetime.now().strftime('%Y%m%d%H%M%S')}.pdf")
    pdf.output(report_path)
    return report_path
